
SET SERVEROUTPUT ON;

-- =====================================================
-- Part 5: View Implementation
-- =====================================================
CREATE OR REPLACE VIEW vw_employee_salary AS
SELECT e.employee_id,
       e.first_name || ' ' || e.last_name AS employee_name,
       e.department_id,
       e.salary
FROM employees e;

CREATE OR REPLACE VIEW vw_employee_details AS
SELECT e.first_name || ' ' || e.last_name AS employee_name,
       d.department_name,
       j.job_title,
       e.salary
FROM employees e
JOIN departments d
  ON e.department_id = d.department_id
JOIN jobs j
  ON e.job_id = j.job_id;

SELECT employee_name,
       department_name,
       job_title,
       salary
FROM vw_employee_details
WHERE salary > 10000
ORDER BY salary DESC;

-- =====================================================
-- Part 6: Procedure Implementation
-- =====================================================
CREATE OR REPLACE PROCEDURE prc_dept_employees (
    p_department_id IN employees.department_id%TYPE
) AS
    l_found BOOLEAN := FALSE;
BEGIN
    FOR r IN (
        SELECT first_name || ' ' || last_name AS employee_name,
               salary
        FROM employees
        WHERE department_id = p_department_id
        ORDER BY employee_id
    ) LOOP
        l_found := TRUE;
        DBMS_OUTPUT.PUT_LINE(r.employee_name || ' - Salary: ' || r.salary);
    END LOOP;

    IF NOT l_found THEN
        DBMS_OUTPUT.PUT_LINE('No employees found in department ' || p_department_id);
    END IF;
END;
/

BEGIN
    prc_dept_employees(60);
END;
/

CREATE OR REPLACE PROCEDURE prc_dept_above_avg (
    p_department_id IN employees.department_id%TYPE
) AS
    l_found BOOLEAN := FALSE;
BEGIN
    FOR r IN (
        SELECT e.first_name || ' ' || e.last_name AS employee_name,
               e.salary
        FROM employees e
        WHERE e.department_id = p_department_id
          AND e.salary > (
              SELECT AVG(e2.salary)
              FROM employees e2
              WHERE e2.department_id = e.department_id
          )
        ORDER BY e.salary DESC
    ) LOOP
        l_found := TRUE;
        DBMS_OUTPUT.PUT_LINE(r.employee_name || ' - Salary: ' || r.salary);
    END LOOP;

    IF NOT l_found THEN
        DBMS_OUTPUT.PUT_LINE(
            'No employee in department ' || p_department_id ||
            ' earns above the department average.'
        );
    END IF;
END;
/

BEGIN
    prc_dept_above_avg(60);
END;
/

-- =====================================================
-- Part 7: Trigger Implementation
-- Create this table only once in your HR practice schema.
-- =====================================================
CREATE TABLE salary_audit (
    audit_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id  NUMBER(6) NOT NULL,
    old_salary   NUMBER(8,2),
    new_salary   NUMBER(8,2),
    update_date  DATE DEFAULT SYSDATE NOT NULL
);

CREATE OR REPLACE TRIGGER trg_salary_audit
AFTER UPDATE OF salary ON employees
FOR EACH ROW
BEGIN
    IF NVL(:OLD.salary, -1) <> NVL(:NEW.salary, -1) THEN
        INSERT INTO salary_audit (
            employee_id,
            old_salary,
            new_salary,
            update_date
        )
        VALUES (
            :NEW.employee_id,
            :OLD.salary,
            :NEW.salary,
            SYSDATE
        );
    END IF;
END;
/

-- Test. This commits an intentional test update for employee 100.
SELECT employee_id, salary
FROM employees
WHERE employee_id = 100;

UPDATE employees
SET salary = salary + 100
WHERE employee_id = 100;

COMMIT;

SELECT audit_id,
       employee_id,
       old_salary,
       new_salary,
       update_date
FROM salary_audit
WHERE employee_id = 100
ORDER BY update_date DESC;

-- =====================================================
-- Task 11 and Change Request 3: Enhanced Audit Fields
-- =====================================================
ALTER TABLE salary_audit ADD (
    username          VARCHAR2(128),
    change_timestamp  TIMESTAMP,
    department_id     NUMBER(4)
);

CREATE OR REPLACE TRIGGER trg_salary_audit
AFTER UPDATE OF salary ON employees
FOR EACH ROW
BEGIN
    IF NVL(:OLD.salary, -1) <> NVL(:NEW.salary, -1) THEN
        INSERT INTO salary_audit (
            employee_id,
            old_salary,
            new_salary,
            update_date,
            username,
            change_timestamp,
            department_id
        )
        VALUES (
            :NEW.employee_id,
            :OLD.salary,
            :NEW.salary,
            SYSDATE,
            USER,
            SYSTIMESTAMP,
            :NEW.department_id
        );
    END IF;
END;
/

-- =====================================================
-- Change Request 1: Full HR View
-- =====================================================
CREATE OR REPLACE VIEW vw_hr_employee_details AS
SELECT e.employee_id,
       e.first_name || ' ' || e.last_name AS employee_name,
       j.job_title,
       d.department_name,
       l.city,
       e.salary
FROM employees e
JOIN jobs j
  ON e.job_id = j.job_id
LEFT JOIN departments d
  ON e.department_id = d.department_id
LEFT JOIN locations l
  ON d.location_id = l.location_id;
